services:

  postgresql:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tododb"

  localstack:
    container_name: localstack
    image: localstack/localstack:latest-amd64
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/localstack/:/etc/localstack/init/ready.d/
