spring:
  application:
    name: todoApp
  datasource:
    url: jdbc:postgresql://localhost/tododb
    username: postgres
    password: postgres
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: ap-northeast-1
      credentials:
        access-key: xxx
        secret-key: yyy

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true